# Generated by Django 3.0.6 on 2020-05-21 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20191216_1230'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autor',
            options={'verbose_name': 'Autor', 'verbose_name_plural': 'Autores'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Artigo', 'verbose_name_plural': 'Artigos'},
        ),
    ]
